// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm0n7JcWX_yKhB5_rdYkbml__aLAQS7eI',
    appId: '1:331474361715:web:c3552ecdf8be3c8c0a3906',
    messagingSenderId: '331474361715',
    projectId: 'cultureguide-25wmr10030-22277',
    authDomain: 'cultureguide-25wmr10030-22277.firebaseapp.com',
    storageBucket: 'cultureguide-25wmr10030-22277.firebasestorage.app',
    measurementId: 'G-V86MTHFSR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa50PmFwgNP8G9A7BREh9eTQaN46WE2jc',
    appId: '1:331474361715:android:de5a231ee9d477490a3906',
    messagingSenderId: '331474361715',
    projectId: 'cultureguide-25wmr10030-22277',
    storageBucket: 'cultureguide-25wmr10030-22277.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtzCCaNKbspvjZXKObxREzcO2qEdW2OMc',
    appId: '1:331474361715:ios:84c9cad11cbf50360a3906',
    messagingSenderId: '331474361715',
    projectId: 'cultureguide-25wmr10030-22277',
    storageBucket: 'cultureguide-25wmr10030-22277.firebasestorage.app',
    iosBundleId: 'com.example.collabDev',
  );
}
